[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]

# Alow foundry to run commands locally in the machine. Needed for DevOpsTools
ffi = true 

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
